std.process: Do not kill process group 2 in unittest
dlang/phobos pull request #10586
Opened 2024-12-12 18:45 UTC by helmutg

When passing a Pid object to tryWait(), its processId will be changed to Pid.terminated, which happens to be -2. Passing this value to kill() will kill the process group 2 on Posix systems. If you run the build and test suite using this process group, the test case will kill the entire build.

Bug-Debian: https://bugs.debian.org/1089007

2024-12-12 19:15 UTC, CyberShadow commented
Thanks, but wouldn't it make more sense to have `kill` throw `ProcessException` if it's passed a `Pid` with `pid == terminated`? That seems to be the intention of the test.

2024-12-12 19:29 UTC, helmutg commented
> Thanks, but wouldn't it make more sense to have `kill` throw `ProcessException` if it's passed a `Pid` with `pid == terminated`? That seems to be the intention of the test.

That is a very reasonable question. Thank you for the review. Is the `kill` function supposed to be able to kill process groups? Do process groups exist on Windows? Does existing code assume that `kill` kills process groups? Whether changing `kill` is better depends on the answers to these questions.

What I am proposing here is a minimum viable solution that makes gcc build rather than fail its build. If changing `kill`, we change behavior and may break other code that assumes the ability to kill process groups. That seems like a risky affair and it feels unlikely that such a patch would be backported into older gcc releases.

2024-12-12 19:34 UTC, CyberShadow commented
> Is the `kill` function supposed to be able to kill process groups?

No, I think it is designed to only kill child processes, created using other `std.process` functions.

> Does existing code assume that `kill` kills process groups?

Seems highly unlikely. The unittest in question seems to assume that `kill` will throw a `ProcessException` if `pid == terminated`, but it passing previously seemed to be accidental and contingent on a process group with the number 2 not existing.

> What I am proposing here is a minimum viable solution that makes gcc build rather than fail its build. If changing `kill`, we change behavior and may break other code that assumes the ability to kill process groups. That seems like a risky affair and it feels unlikely that such a patch would be backported into older gcc releases.

True. We can go forward with this change as well, though I would add a `TODO` to note that the condition may not be what was originally intended to be tested.

Let's see what other Phobos maintainers say as well. @schveiguy ?

2024-12-13 18:05 UTC, toote commented
A few lines above there is a similar assertion stating that negative pids should not be allowed. But that line suffers from the same issue: if the PID exists, it will kill the group instead of raising the exception.

https://github.com/dlang/phobos/blob/8973596c05d4bcb9fc8ef735f06618ed2209a05e/std/process.d#L2853

2024-12-29 10:05 UTC, rikkimax requested changes

2024-12-29 10:05 UTC, rikkimax commented on std/process.d
> +    assert(pid.processID == Pid.terminated);
Please rewrite this to use ``assertThrown`` as the unittest previously used, unless you have a reason to not do so.

2024-12-29 10:15 UTC, rikkimax commented on std/process.d
> +    assert(pid.processID == Pid.terminated);
Nevermind. Not what I thought it did, ``assert`` is fine.

2024-12-29 10:46 UTC, CyberShadow commented
https://github.com/dlang/phobos/pull/10601

2024-12-29 12:08 UTC, helmutg commented
> #10601

My understanding is that the proposed MR obsoletes this MR if merged, but I am not convinced that it is eligible for backporting into older gcc releases.

2024-12-29 12:43 UTC, helmutg commented
> Why is that? What would make it eligible?

Your change is changing semantics. Effectively, you'd have to provide a good argument for why it cannot break existing code that relies on the unintended behavior.  You cannot provide such a proof. Hence, I do not expect your change to be backportable.

Keep in mind that there are two partially distinct bugs here:
 1. Running the libphobos test suite kills the entire gcc build.
 2. `kill` does not reliably raise an exception for invalid `Pid` objects.

The first of these is something we want to resolve in older releases, because they fail to build. It is not as clear that we also need to fix the latter in old releases.

2024-12-29 13:06 UTC, helmutg commented
That sounds like a strong reason. I appreciate if you can try getting this ported to gcc versions 15, 14, 13, 12, 11 and 10.

2024-12-29 13:24 UTC, CyberShadow commented
@ibuclaw Is that something we can do?

2024-12-29 16:29 UTC, schveiguy commented
> My understanding is that the proposed MR obsoletes this MR if merged

I think that is correct.

2024-12-29 16:29 UTC, closed without merging