Help compiler deduce `pure` for moveEmplaceImpl
dlang/phobos pull request #7670
Opened 2020-10-20 13:12 UTC by JohanEngelen

This fixes https://issues.dlang.org/show_bug.cgi?id=21202 .

This puts no extra requirements on `moveEmplaceImpl`. `moveEmplaceImpl` already has to be `pure` because `moveEmplaceImpl` is called by `moveEmplace` which is explicitly marked `pure`.

2020-10-20 13:19 UTC, MoonlightSentinel requested changes
> This puts no extra requirements on moveEmplaceImpl. moveEmplaceImpl already has to be pure because moveEmplaceImpl is called by moveEmplace which is explicitly marked pure.

But breaks `move` which doesn't have this requirement and calls user-defined `opAssign`/`opPostMove`

2020-10-21 12:41 UTC, kinke commented
I'm shocked to see this stuff is still in `std.algorithm.mutation` - hasn't this all been moved to `core.lifetime`?!

2020-10-21 15:05 UTC, wilzbach commented
Yes, but we couldn't remove this as there was one compile-time check that pulled in the world (about 2k of additional templates to druntime)

2020-10-21 15:10 UTC, wilzbach commented
Details: https://github.com/dlang/phobos/pull/6848

2020-10-26 15:52 UTC, edi33416 commented on std/algorithm/mutation.d
> +unittest
Can you please add attributes for the unittest block?

2020-10-26 15:57 UTC, edi33416 commented
What stops the compiler from inferring the `pure`ness of `moveEmplaceImpl`?

2020-10-26 15:59 UTC, edi33416 commented
> But breaks `move` which doesn't have this requirement and calls user-defined `opAssign`/`opPostMove`

What if you put the function body in a `pure` lambda? Then the compiler should be able to infer the purity and the change won’t break `move`

2021-01-13 13:13 UTC, RazvanN7 commented
@JohanEngelen Why is this necessary? The compiler should be able to deduce the purity of that function.

2021-01-13 16:35 UTC, JohanEngelen commented
> @JohanEngelen Why is this necessary? The compiler should be able to deduce the purity of that function.

See https://issues.dlang.org/show_bug.cgi?id=21202

2021-01-13 16:36 UTC, JohanEngelen commented
(based on some of the comments, I am no longer convinced this is the correct fix, but the issue still stands)

2021-04-13 10:12 UTC, RazvanN7 commented
@JohanEngelen It is bad practice to force an attribute on a template (especially one that potentially calls user-defined functions). This is more likely a compiler bug.

I'm going to close this PR and investigate this to get to the bottom of it.

I will close this PR as this is most likely not fixing the root cause. Please reopen if you have anything else to add.

2021-04-13 10:12 UTC, closed without merging

2021-04-13 20:12 UTC, JohanEngelen commented
@RazvanN7 Thanks for looking into fixing the compiler. This workaround is still needed at Weka.

2021-04-22 13:24 UTC, RazvanN7 commented
@JohanEngelen I have looked into it and it looks like a compiler bug: https://issues.dlang.org/show_bug.cgi?id=21850 .