Nullable isNotNull
dlang/phobos pull request #7706
Opened 2020-11-25 15:12 UTC by burner

I find myself typing !var.isNull so often.

So much so that I think var.isNotNull would make my code look so much better.

2020-11-25 15:46 UTC, atilaneves commented
I'm not sure this is worth adding.

2020-11-25 16:30 UTC, Geod24 requested changes
I don't see the point of this. `!var.isNull()` is shorter, easy to understand, and already well established.

2020-11-26 07:50 UTC, burner commented
fair enough, I just found it so annoying 

because my brain is not thinking in an order similar to "not is some condition" but rather "is not condition" must be a native German speaking thing.

didn't take long to write this PR, I hope I didn't waste to much of your guys time.

2020-11-26 07:50 UTC, closed without merging

2020-12-03 22:20 UTC, PetarKirov commented
What do you guys think about:

```D
bool opCast(T : bool)() { return !isNull; }
```

So that one could do:
```D
if (var) { }
```

instead?

2020-12-04 07:44 UTC, burner commented
Idk, I'm not really a fan.