Add ilog2.
dlang/phobos pull request #7939
Opened 2021-04-06 14:14 UTC by berni44

The idea of `std.math.integral` is to add some functions on integers, that are often useful.

I start with a rather simple one: `ilog2`, which calculates logarithm on base 2 and rounds the result down to the next integer. This is useful for algorithms, that have to do estimates based on the size of a value. E.g. `1 << (ilog2(x)/2)` can be used as a seed for herons's method adapted for integral square root calculation.

The implementation is the fastest I'm aware of. Average computation time for `longs` is on my computer about 0.01ns, using ldc2 with optimization turned on.

2021-04-08 10:23 UTC, RazvanN7 commented
cc @atilaneves

2021-04-08 10:23 UTC, RazvanN7 reviewed
Looks good to me.

2021-04-08 11:58 UTC, dkorpel requested changes
The implementation can be simplified to:
```D
Unqual!Int ilog2(Int)(Int value)
{
    import core.bitop: bsr;
    if (value <= 0) return 0;
    return cast(typeof(return)) bsr(value);
}
```
Scanning for the most significant bit has a special instruction on most processors, and druntime has a function exposing it (with a fast software fall-back).

2021-04-08 13:03 UTC, ibuclaw requested changes
Use `bsr` - though I wonder if we really need a new function for something that is just a trivial shell around another.

2021-04-08 13:20 UTC, berni44 commented
> Scanning for the most significant bit has a special instruction on most processors, and druntime has a function exposing it (with a fast software fall-back).

Oh, thanks - I didn't know that.

2021-04-08 13:27 UTC, berni44 commented
> Use `bsr` - though I wonder if we really need a new function for something that is just a trivial shell around another.

Well, just the fact, that I did not know about `bsr` reveals already, that there is some need. OK, I didn't look into `druntime`, admitted. But anyway, I would have overlooked `bsr`, because it's name doesn't tell one anything, when not being familiar with processor instructions. And well, in some sense it's a coincidence, that the position of the leftmost bit and `log2` is the same for integers. With `ilog10` this doesn't work anymore and people may wonder why `ilog2` was not implemented. For example look at [issue 9300](https://issues.dlang.org/show_bug.cgi?id=9300). If the author of that issue would have been aware of `bsr` he would probably have chosen a different example...

2021-04-12 15:19 UTC, atilaneves commented
> > Use `bsr` - though I wonder if we really need a new function for something that is just a trivial shell around another.
> 
> Well, just the fact, that I did not know about `bsr` reveals already, that there is some need. OK, I didn't look into `druntime`, admitted. But anyway, I would have overlooked `bsr`, because it's name doesn't tell one anything, when not being familiar with processor instructions. And well, in some sense it's a coincidence, that the position of the leftmost bit and `log2` is the same for integers. With `ilog10` this doesn't work anymore and people may wonder why `ilog2` was not implemented. For example look at [issue 9300](https://issues.dlang.org/show_bug.cgi?id=9300). If the author of that issue would have been aware of `bsr` he would probably have chosen a different example...

Is bsr literally the same thing? If so we definitely don't need two functions.

2021-04-12 16:35 UTC, berni44 commented
> Is bsr literally the same thing? If so we definitely don't need two functions.

`std.math` contains several functions that are merely wrappers around a function of `druntime`, e.g. several of the trigonometric functions, or `rint`, `fabs` or `sqrt`. And funnily (I didn't know that before I just yet scanned through the package): An overload of [`ilogb`](https://dlang.org/phobos/std_math.html#.ilogb) for integers which is essentially, what I suggest here... *g*

2021-04-12 16:35 UTC, closed without merging