std.math: Move most of the rounding functions into submodule.
dlang/phobos pull request #7943
Opened 2021-04-07 13:13 UTC by berni44

I left out `floor` and `ceil` because moving `floorImpl` to the submodule fails with a strange error message. I guess, there is some compiler magic involved here, making `union` work in CTFE.

2021-04-07 15:08 UTC, berni44 commented
Here `compilable/test5227.d` fails. It's two function that cannot be evaluated at runtime: `round` and `trunc`. Looks, like the calls to `core.stdc.math.roundl` and `core.stdc.math.truncl` in CTFE are restricted to `std.math`, but cannot be called from `std.math.rounding`.

2021-04-07 16:01 UTC, berni44 commented
It's not the calls I mentioned above. So I suspect dmd searching `round` and `trunc` in `std.math` and not in `std.math.rounding`; that is, the public imports are ignored... I need help here from someone who knows the inner workings of dmd.

2021-04-08 01:34 UTC, thewilsonator commented
https://github.com/dlang/dmd/blob/master/src/dmd/builtin.d#L91 is the function in question.

2021-04-08 10:17 UTC, RazvanN7 commented
Have you tried making a public alias to the symbols that were moved to the submodules? That should work.

Otherwise, we can make the compiler acknowledge the new submodules, although I would rather not go down that route.

2021-04-08 11:26 UTC, berni44 commented
> Have you tried making a public alias to the symbols that were moved to the submodules? That should work.

Wouldn't that clash with the public imports? I'll check it out.

2021-04-08 13:37 UTC, berni44 commented
Didn't clash, so I probably do not understand something with visibility and scope... But that's my fault. I'll try to pick that up.

Anyway, the error has not vanished, but this time brought up a new detail:

```
D:\a\1\dmd\test\..\..\phobos\std\math\package.d(4851): Error: `asm` statements cannot be interpreted at compile time
D:\a\1\dmd\test\..\..\phobos\std\math\rounding.d(437):        called from here: `getControlState()`
compilable\test5227.d(70):        called from here: `round(5.5L)`
compilable\test5227.d(70):        while evaluating `pragma(msg, roundr)`
```

Line 4851 of `package.d` is inside `getControlState()` of `FloatingPointControl`.

2021-04-11 05:38 UTC, ibuclaw requested changes
Squash and add missing versions.

2021-04-11 05:38 UTC, ibuclaw commented on std/math/rounding.d
> +    version (InlineAsm_X87)
Missing version definition at top of file.

2021-04-11 05:38 UTC, ibuclaw commented on std/math/rounding.d
> +    version (InlineAsm_X87_MSVC)
Missing version definition

2021-04-11 05:38 UTC, ibuclaw commented on std/math/package.d
> +public alias trunc = std.math.rounding.trunc;
Remove this as is unnecessary

2021-04-11 05:38 UTC, ibuclaw commented on std/math/rounding.d
> +
```suggestion

version (D_InlineAsm_X86)    version = InlineAsm_X86_Any;
version (D_InlineAsm_X86_64) version = InlineAsm_X86_Any;

version (InlineAsm_X86_Any) version = InlineAsm_X87;
version (InlineAsm_X87)
{
    static assert(real.mant_dig == 64);
    version (CRuntime_Microsoft) version = InlineAsm_X87_MSVC;
}

```

2021-04-11 08:17 UTC, ibuclaw approved these changes

2021-04-12 00:15 UTC, merged