Partially solve issue 18161 - splitWhen and most of chunkBy now @safe
dlang/phobos pull request #8213
Opened 2021-08-25 18:58 UTC by dukc

To be more precise, I made `chunkBy` infer `@safe` with forward ranges. Didn't touch the non-forward range implementation.

As always with marking formerly `@system` code `@safe`, reviewing definitely welcome.

2021-08-29 13:57 UTC, pbackus requested changes

2021-08-29 13:57 UTC, pbackus commented on std/algorithm/iteration.d
> +        mothership = temp;
Please add a comment explaining what these lines do and why they're necessary.

2021-08-29 13:57 UTC, pbackus commented on std/algorithm/iteration.d
> +        _impl = temp;
Ditto.

2021-08-30 13:49 UTC, pbackus approved these changes

2021-08-31 06:10 UTC, RazvanN7 approved these changes

2021-08-31 06:10 UTC, merged