Use version (StdUnittest) for the unittests that need it
dlang/phobos pull request #8230
Opened 2021-09-03 14:54 UTC by nordlow

Shall `version(StdUnittest)` all `unittest`s in phobos to speed up compilation?

2021-09-03 19:26 UTC, dukc requested changes
I may be wrong with this, but I think the unit tests are best left as is. `version(StdUnittest)` is probably intended to avoid slowing compilation when unit testing client code, but I think unit test blocks in Phobos are skipped anyway. `version(StdUnittest)` in front of them just add bloat, and if you accidently unit test Phobos without `-version=StdUnittest` you probably want an error that you're not testing everything.

2021-09-03 19:34 UTC, nordlow commented
> I may be wrong with this, but I think the unit tests are best left as is. `version(StdUnittest)` is probably intended to avoid slowing compilation when unit testing client code, but I think unit test blocks in Phobos are skipped anyway. `version(StdUnittest)` in front of them just add bloat, and if you accidently unit test Phobos without `-version=StdUnittest` you probably want an error that you're not testing everything.

Ok, this PR anyhow fixes the compilation of pass when -version=StdUnittest is not given. Have anybody benchmark compiling an application with phobos with -unittest activated with all unittests in phobos tagged with version(StdUnittest). If not it's worth investigating how large of a speed that gives.

2021-09-03 21:12 UTC, ljmf00 commented
> > I may be wrong with this, but I think the unit tests are best left as is. `version(StdUnittest)` is probably intended to avoid slowing compilation when unit testing client code, but I think unit test blocks in Phobos are skipped anyway. `version(StdUnittest)` in front of them just add bloat, and if you accidently unit test Phobos without `-version=StdUnittest` you probably want an error that you're not testing everything.
> 
> Ok, this PR anyhow fixes the compilation to pass when `-unittest` is given but `version(StdUnittest)` is false. Some modules in this settings so I see no reason for other modules to not pass
> 
> Btw, have anybody benchmarked compiling an application with phobos with `-unittest` activated with all unittests in phobos tagged with `version(StdUnittest)`? If not it's worth investigating how large of a speed up that gives.

If this makes Phobos compilable without that `version` flag I favourably agree on this. Also making Phobos compilation faster is desired. Although adding this to *every* unittest seems bloated and a good advantage need to compensate it.

2021-09-06 12:28 UTC, RazvanN7 commented
The primary purpose of `version(StdUnittest)` was to be able to test phobos features with declarations that cannot be declared at function scope (such as overloaded function declarations or templated functions; the latter seems to compile now, so I guess we could get rid of some of the use cases of StdUnittest). I don't know if other use cases arouse, but the general rule of thumb is to get rid of StdUnittest, not add more.

> because these unittests use symbols that are hidden behind version(StdUnittest).

`version(StdUnittest)` is set automatically in the makefile when phobos is compiled with -unittest, so I don't see the point of this change.

> Also making Phobos compilation faster is desired

Why would this change make phobos compilation faster?

2021-09-06 12:41 UTC, nordlow commented
> The primary purpose of `version(StdUnittest)` was to be able to test phobos features with declarations that > Why would this change make phobos compilation faster?

It doesn't. It just make the module compile with `-unittest` but without `version(StdUnittest)` set. It just discovered this because my Emacs FlyCheck configuration used these settings.

2021-09-09 15:42 UTC, RazvanN7 commented
@nordlow 

> version(StdUnittest) is set automatically in the makefile when phobos is compiled with -unittest, so I don't see the point of this change.

I still don't understand what is the motivation for this PR. Can you come up with a real life example where not having these versions is a problem?

2021-09-09 17:55 UTC, nordlow commented
> @nordlow
> 
> > version(StdUnittest) is set automatically in the makefile when phobos is compiled with -unittest, so I don't see the point of this change.
> 
> I still don't understand what is the motivation for this PR. Can you come up with a real life example where not having these versions is a problem?

It adds `version(StdUnittest)` to the unittests that fail to compile when `StdUnittest` is not defined. Provided `-unittest` is used.

2021-09-13 10:11 UTC, RazvanN7 commented
I think that `StdUnittest` should, ideally, disappear from phobos. That might not be possible in all cases, but as rule of thumb we should strive to have as little as possible, not to add more.

Compilation of phobos with unittest is likely done using the existing makefiles and if anyone wants to mimic that behavior, then consulting the said makefiles is the way to go. Therefore, I am going to close this. Thanks anyway for the effort!

2021-09-13 10:11 UTC, closed without merging