Qualify some function parameters under std.conv as const to reduce te…
dlang/phobos pull request #8251
Opened 2021-09-23 10:29 UTC by nordlow

…mplate bloat

2021-09-23 10:49 UTC, thewilsonator approved these changes

2021-09-24 10:24 UTC, PetarKirov commented
@nordlow unit-threaded fails to compile with this change:

```
Cloning https://github.com/atilaneves/unit-threaded (tag: v2.0.3)
Running the testsuite
~> case "$REPO_FULL_NAME" in
~> dub test
Running custom 'unittest' configuration.
Performing "unittest" build using /var/lib/buildkite-agent/builds/ci-agent-7d11ce47-aa1b-4308-a8a5-39b5bb0de700-2/dlang/phobos/build/distribution/bin/dmd for x86_64.
unit-threaded:from 2.0.3: building configuration "library"...
unit-threaded:exception 2.0.3: building configuration "library"...
unit-threaded:assertions 2.0.3: building configuration "library"...
unit-threaded:integration 2.0.3: building configuration "library"...
unit-threaded:mocks 2.0.3: building configuration "library"...
unit-threaded:property 2.0.3: building configuration "default"...
unit-threaded:runner 2.0.3: building configuration "library"...
subpackages/runner/source/unit_threaded/runner/factory.d(55,24): Error: template `std.conv.text` cannot deduce function from argument types `!()(string, const(TestData))`
/var/lib/buildkite-agent/builds/ci-agent-7d11ce47-aa1b-4308-a8a5-39b5bb0de700-2/dlang/phobos/build/distribution/bin/../imports/std/conv.d(4738,8):        Candidate is: `text(T...)(const(T) args)`
subpackages/runner/source/unit_threaded/runner/testcase.d(274,39): Error: template `std.conv.text` cannot deduce function from argument types `!()(string, string, string, const(TypeInfo), string, TypeInfo_Class)`
/var/lib/buildkite-agent/builds/ci-agent-7d11ce47-aa1b-4308-a8a5-39b5bb0de700-2/dlang/phobos/build/distribution/bin/../imports/std/conv.d(4738,8):        Candidate is: `text(T...)(const(T) args)`
```

2021-09-24 15:00 UTC, nordlow commented
> subpackages/runner/source/unit_threaded/runner/factory.d(55,24): Error: template `std.conv.text` cannot deduce function from argument types `!()(string, const(TestData))`

This passes when I change 

```d
const(T) args
```

to 
d
```
const T args
```

. What is the difference now again?

Both cases reduce template bloat in my measurements.

Ping, @adamdruppe.

2024-12-28 23:54 UTC, thewilsonator approved these changes

2024-12-29 01:08 UTC, 0xEAB commented
> Unfortunately using `const T args` makes `make -f posix.mak unittest` fail in several places because std.format doesn't yet correctly handles ranges passed by const. We could define an overload that passes only non-ranges by const. Both cases reduce template bloat in my measurements.

Indeed.

```d
static struct Range
{
	int counter = 0;

@safe pure nothrow @nogc:
	bool empty() const => (counter <= 0);
	int front() const => counter;
	void popFront() { --counter; }
}

auto m = Range(2);
```
… would get printed as `const(Range)(2)` instead of `[2, 1]`.
And I don’t think we can blame the library; a const range that you can’t pop-front is a dead end – kinda.

2024-12-29 02:38 UTC, 0xEAB commented
CI failures are expected; this patch is still flawed.

2025-03-15 03:13 UTC, pbackus requested changes
This caused regressions when it was done in `std.format` (PR #8249), and it will cause regressions here too. **This PR must not be merged.**

2025-03-15 03:25 UTC, 0xEAB commented
Having had a glimpse at <https://github.com/dlang/phobos/pull/8591/files#diff-0cefbc614b4b0ed8ef2e594905dddb131963e859be1af0068c9bb5b7b129ba89>, I suppose this won’t be solvable realistically – right?

2025-03-15 12:46 UTC, pbackus commented
No, this is not solvable—not even in principle.

In general, if a use passes a value of an arbitrary type into generic code, and the generic code wants to use that value to call other functions/methods, it must preserve the *exact* type (including qualifiers) of the value in order to call the correct overload(s).

2025-03-16 01:26 UTC, 0xEAB commented
Phantom-zoning this.
If someone disagrees and considers this salvageable, feel free to re-open (and tag accordingly).

2025-03-16 01:26 UTC, closed without merging