Fix issue 21507 - added precision for function SysTime.toIsoExtString
dlang/phobos pull request #8255
Opened 2021-09-28 19:48 UTC by lucica28

This pull request is aimed to solve the issue that toIsoExtString outputs a variable number of characters and this can break the alignment of documents.

2021-09-29 05:32 UTC, PetarKirov approved these changes

2021-09-29 06:30 UTC, RazvanN7 requested changes

2021-09-29 06:30 UTC, RazvanN7 commented on std/datetime/systime.d
> +        Parameter "prec" allows to get rid of the variance present as default
```suggestion
        The optional parameter "prec" allows to change the default behavior by specifying the precision of the fractional seconds. The accepted values are in the range [-1, 7], where -1 represents the default behavior.
```

2021-09-29 06:30 UTC, RazvanN7 commented on std/datetime/systime.d
> +            prec = An `int`
```suggestion
            prec = An `int` representing the desired precision. Acceptable values range from -1 to 7, where -1 represents the default behavior.
```

2021-09-29 06:30 UTC, RazvanN7 commented on std/datetime/systime.d
> +    assert(prec >= -1 && prec <= 7);
This assert should be moved to the user-facing functions. You don't want to have an assert failing inside the innards of a private function, leaving the user with no idea of what he did wrong. I suggest moving this assert to the `toISOExtString` functions and also putting an informative assert message, e.g  `assert(prec >= -1 && prec <=7, "Precision must be in the range [-1, 7]");`

2021-09-30 06:27 UTC, RazvanN7 approved these changes

2021-09-30 06:50 UTC, merged