Fix issue 22701: Remove is(typeof()) callable check in std.typecons.apply.
dlang/phobos pull request #8364
Opened 2022-01-24 11:47 UTC by FeepingCreature

To quote my bug report:

> As I said in my DConf talk, `__traits(compiles)` is Satan, the Great Deceiver. The presence of is(typeof()) in the definition of `apply` needlessly turns a clear, readable error in the passed lambda into an incomprehensible template error that requires advanced language knowledge or blind guessing to untangle. And there's no point, because there's only one apply function! It should just be removed.

(Let's see if this passes the testsuite!)

2022-01-24 14:20 UTC, FeepingCreature commented
Errors seem spurious.

2022-01-26 11:28 UTC, RazvanN7 commented
@FeepingCreature please rebase. That will fix the testing pipeline.

2022-01-26 11:51 UTC, RazvanN7 requested changes
Could you provide an example where the error message is improved with this patch? I tested this (adapted from the public unittest):

```d
import std.typecons;

void main()
{
    Nullable!int sample;   
    Nullable!float f;
    sample = 3;
    
    f = sample.apply!sample;  
}
```

And I get the following results:

1. Before patch: 

```
onlineapp.d(9): Error: template `onlineapp.main.apply!(sample).apply` cannot deduce function from argument types `!()(Nullable!int)`
/dlang/dmd/linux/bin64/../../src/phobos/std/typecons.d(4038):        Candidate is: `apply(T)(auto ref T t)`
  with `T = Nullable!int`
  must satisfy the following constraint:
`       is(typeof(unaryFun!fun(T.init.get)))`
```

2. After patch:

```
phobos/std/typecons.d(4047): Error: struct `Nullable` does not overload ()
phobos/std/typecons.d(4068): Error: struct `Nullable` does not overload ()
test.d(9): Error: template instance `test.main.apply!(Nullable!int)` error instantiating
```

Note how this patch moves the failure in the innards of the `apply` function.

2022-01-26 11:59 UTC, FeepingCreature commented
Sure, for example:

```
import std.typecons;
void main() {
    Nullable!int foo;
    auto twice = foo.apply!(a => a ~ a);
}
```

Without patch:
```
test.d(4): Error: none of the overloads of template `test.main.apply!((a) => a ~ a).apply` are callable using argument types `!()(Nullable!int)`
dmd/generated/linux/release/64/../../../../../phobos/std/typecons.d(4044):        Candidate is: `apply(T)(auto ref T t)`
  with `T = Nullable!int`
  must satisfy the following constraint:
`       is(typeof(unaryFun!fun(T.init.get)))`
```

With patch:
```
test.d(4): Error: incompatible types for `(a) ~ (a)`: both operands are of type `int`
test.d(4):        instantiated from here: `apply!(Nullable!int)`
```

2022-01-27 10:18 UTC, RazvanN7 commented
I understand that the current error message is not ideal, however:

1. It does specify which constraint you are not respecting, therefore giving a hint on what is wrong.
2. For whatever combination of wrong arguments you will not be presented with failing code in the innards of `apply`.

This patch, however, opens the door to issuing errors from inside the implementation of `apply` and I personally
don't see how the new error message that you pasted is better. It just says that `int` is incompatible for `~` however
it does not give you any indication on how to fix this because it is entirely omitting the fact that you are working with a Nullable.
Imagine that you are working with voldemort types that you are passing to apply, something along the lines of:

```d
auto v = someFunctionReturningNullableOfInt();
v.apply!(a => a ~ a);    // error: incompatible type int for ~; ok what do I do now? 
```

This, in my opinion, is more confusing then presenting a condition which has failed. With the current status you can simply copy that condition and run it in a separate file and see why it failed, plus all the actual types are included in the error message.

2022-01-27 11:39 UTC, FeepingCreature commented
> it is entirely omitting the fact that you are working with a Nullable.

> > test.d(4):        instantiated from here: `apply!(Nullable!int)`

In my experience with Nullable, maybe 90% of the time the issue is a semantic error *inside the lambda.* The issue is almost never an error in apply itself. And if it was, that would be the sort of issue that you can apply inside knowledge to solving. Semantic errors in the lambda are the thing that's most plausible to turn up in user code, which is exactly the target group where vague, content-free hints like `is(typeof(unaryFun!fun(T.init.get)))` (which relies on two expert-level D interna, `is(typeof())` and `unaryFun`) are at their most harmful.

2022-01-27 12:13 UTC, RazvanN7 commented
I, personally, would concede in front of real life experience with `Nullable` since I don't use it in my day to day programming routine. However, I would like another heavy user of `Nullable` to weight in on this. @burner do you have any opinions on this?

2022-01-27 14:18 UTC, burner commented
Only, that I have not used apply that much. Like once or twice. But in general I'm not a fan of template constraint in general.
As there is no overloading for apply pulling the constraint into a static assert inside of the function and then generating a nice(r) error would be "better".

2022-01-27 16:50 UTC, moon-chilled commented
I will say: I recently made a very similar change at fork for the exact same reason: error messages were incomprehensible without, useful with.  (That said I have not used apply.  But seeing as feep did, ran into the same issue, this seems quite reasonable.)

2022-01-28 08:25 UTC, RazvanN7 commented
@FeepingCreature this

> Only, that I have not used apply that much. Like once or twice. But in general I'm not a fan of template constraint in general.
As there is no overloading for apply pulling the constraint into a static assert inside of the function and then generating a nice(r) error would be "better".

Would be ideal.

2022-01-28 08:56 UTC, FeepingCreature commented
Not sure how to do that? The error that I want is inside the lambda. If I static assert something in apply, wouldn't that error suppress the error in the lambda?

2022-01-28 08:59 UTC, burner commented
I would compare type of the parameter of the passed function with the T of the Nullable.

When you get a void != int you likely know where to look.

2022-01-28 11:35 UTC, FeepingCreature commented
Well, with a lambda you don't have a passed type. I guess I should add a `std.functional` template that checks everything that can be statically checked, without trying to instantiate the argument if it's a template? Then that can replace is(typeof()) in the incondition?

2022-01-29 09:59 UTC, RazvanN7 commented
Ok, let's just merge as is and we can improve on it in the future if needed.

2022-01-29 10:00 UTC, RazvanN7 approved these changes

2022-01-29 10:00 UTC, merged