std.algorithm.searching.balancedParens: make function nothrow for char types
dlang/phobos pull request #8550
Opened 2022-08-30 22:07 UTC by wolframw

This improves the somewhat hacky implementation of #8547 and, more generally, makes `std.algorithm.searching.balancedParens` `nothrow` when both the range's element type and `E` are either `char`, `wchar`, or `dchar`.

2022-08-30 22:54 UTC, wolframw commented
Not sure why the logger unittest fails on the auto-tester. My guess is it's the same problem as this: https://issues.dlang.org/show_bug.cgi?id=23286

2022-08-31 00:14 UTC, thewilsonator approved these changes

2022-08-31 03:15 UTC, Geod24 requested changes
This is diverging from the auto-decoding practice done elsewhere.
Don't get me wrong, I like the change, but it makes this algorithm inconsistent with the other ones.

2022-08-31 10:22 UTC, wolframw commented
> This is diverging from the auto-decoding practice done elsewhere. Don't get me wrong, I like the change, but it makes this algorithm inconsistent with the other ones.

I see... I guess one alternative would be to wrap `rn.front` into a `try`-`catch (UTFException e)` block and manually use the replacement char as a fallback in the `catch` block (or just skip in that case?).

Did you have anything specific in mind when you wrote https://github.com/dlang/phobos/pull/8547#issuecomment-1229814392?

2022-09-01 07:41 UTC, Geod24 commented
> Did you have anything specific in mind when you wrote https://github.com/dlang/phobos/pull/8547#issuecomment-1229814392?

I was thinking of doing what you did (`.byUTF` on the string) at the call-site, not to change `balancedParens`.

2022-09-02 05:39 UTC, Geod24 approved these changes
Neat!

2022-09-05 07:27 UTC, RazvanN7 approved these changes

2022-09-26 02:47 UTC, RazvanN7 approved these changes

2022-09-26 02:47 UTC, merged