std.socket: replace static this with crt_constructor
dlang/phobos pull request #8670
Opened 2023-01-26 08:29 UTC by WalterBright

This is the only `static this` left in Phobos. Removing it makes for reducing need for ModuleInfo.

2023-01-26 18:21 UTC, Geod24 commented
What's the purpose here ?

2023-01-26 18:23 UTC, ibuclaw commented
Seriously? No.

2023-01-26 19:48 UTC, WalterBright commented
As in core.cpuid, the reason is having a static this means that a ModuleInfo will need to be generated for every object file that imports it. Since the static constructor has no dependencies on any other module, by initializing it with the C library constructor will not produce such dependencies.

2023-01-26 19:50 UTC, WalterBright commented
It's just good engineering to eliminate unnecessary dependencies.

2023-01-26 19:51 UTC, WalterBright commented
ModuleInfo also gets in the way of using betterC, which does not support ModuleInfo.

2023-01-26 19:59 UTC, ibuclaw commented
None of these are actually eliminating dependencies.  Rather making it harder for people to use them without C.

2023-01-26 20:47 UTC, WalterBright commented
> None of these are actually eliminating dependencies.

It eliminates the dependency on ModuleInfo and the dependency on druntime.

> Rather making it harder for people to use them without C.

All pragma(crt_constructor) actually does is put a pointer to the function in a named section. Besides, `std.socket` relies on the existence of an operating system anyway, and that operating system will have the C standard library on board.

2023-01-26 23:12 UTC, ljmf00 requested changes
Please don't do this:
- It will possibly be using uninitialized GC, which can be catastrophic
- It uses exceptions, which depends on runtime initialization anyway

> As in core.cpuid, the reason is having a static this means that a ModuleInfo will need to be generated for every object file that imports it. Since the static constructor has no dependencies on any other module, by initializing it with the C library constructor will not produce such dependencies.

This is a clear reason to fix the ModuleInfo ABI. I remember @deadalnix telling me how broken ModuleInfo is on DMD at DConf. Why don't we implement order independent construction and add a priority tag to it? People already need to do shenanigans to make independent construction working and it possibly doesn't work on separate compilation module, due to how ModuleInfo is designed.

It's also an annoying real issue I have at production code with huge inter-module dependencies. Every time I include a module with a `static this` that also includes itself indirectly gets broken at runtime, on runtime initialization, and this is the biggest flaw of ModuleInfo.

We can surely implement something that doesn't need the requirement above mentioned by you, just like what C does. Also, ABI breakage isn't a reason to not change this, because the ABI is already broken.

2023-01-26 23:15 UTC, ibuclaw commented
> All pragma(crt_constructor) actually does is put a pointer to the function in a named section.

And so does `shared static this`.

> Besides, `std.socket` relies on the existence of an operating system anyway, and that operating system will have the C standard library on board.

It also still relies on the existence of a D runtime, what with its use of `new`, exceptions, rtti, dynamic arrays, etc...

Anyway, this is not the way to do it.

2023-01-26 23:16 UTC, ibuclaw requested changes
See #5470 for an example of eliminating static this.

2023-01-26 23:18 UTC, CyberShadow commented
Another approach to this:

- https://github.com/dlang/phobos/pull/5813

2023-01-27 04:53 UTC, WalterBright commented
> #5813

 108 lines of changes, abandoned as too much work

> #5470

Also by Andrei, also a lot of work. Yeah, one could do lazy initialization, though one would lose the advantages of immutable variables.

> And so does shared static this.

Yes, but `shared static this` comes with a requirement for `ModuleInfo`

> It also still relies on the existence of a D runtime, what with its use of new, exceptions, rtti, dynamic arrays, etc...

Yes, but does not require `ModuleInfo`

> It will possibly be using uninitialized GC, which can be catastrophic. It uses exceptions, which depends on runtime initialization anyway

The constructor does indeed throw, good catch. This can be fixed, as the error is fatal anyway.

> I remember @deadalnix telling me how broken ModuleInfo is on DMD

I wish people would include bugzilla references when making statements like this.

> It's also an annoying real issue I have at production code with huge inter-module dependencies.

Ironically, that's a reason for this PR.

2023-01-27 05:04 UTC, WalterBright commented
> Every time I include a module with a static this that also includes itself indirectly gets broken at runtime, on runtime initialization, and this is the biggest flaw of ModuleInfo.

Both modules have to have a `static this` to trigger an error. The error is:
```
object.Error@src/rt/minfo.d(364): Cyclic dependency between module constructors/destructors of test4x and test4
```
which is deliberate. With these cycles, how is the compiler to know which one gets run first? (At least D detects the error, with C one will arbitrarily get run first. If that isn't the right order, too bad.)

The solution is the user will have to specify which one comes first. The way to do that is to create a third module with just the static constructor in it that needs to run first, and have both modules import that module. That eliminates the dependency loop.

I don't know of any other way to do it that would be robust.

2023-01-27 05:05 UTC, WalterBright commented
BTW, this `static this` is the *last* static constructor left in Phobos. Wouldn't it be nice to have it gone, too?

2023-01-27 10:17 UTC, ljmf00 commented
> > Every time I include a module with a static this that also includes itself indirectly gets broken at runtime, on runtime initialization, and this is the biggest flaw of ModuleInfo.
> 
> Both modules have to have a `static this` to trigger an error. The error is:
> 
> ```
> object.Error@src/rt/minfo.d(364): Cyclic dependency between module constructors/destructors of test4x and test4
> ```
> 
> which is deliberate. With these cycles, how is the compiler to know which one gets run first? (At least D detects the error, with C one will arbitrarily get run first. If that isn't the right order, too bad.)

Not both modules imported directly, but if they indirectly import one that has a `static this`, this happens. I understand the rationale of having this on the current implementation of ModuleInfo, but the thing is: we can provide alternatives, as already discussed in the forum for this problematic.

> The solution is the user will have to specify which one comes first. The way to do that is to create a third module with just the static constructor in it that needs to run first, and have both modules import that module. That eliminates the dependency loop.
> 
> I don't know of any other way to do it that would be robust.

The creation of another module is the shenanigans I was talking about. And due to how ModuleInfo is designed, it potentially doesn't run. That works on one compiler invocation, but what if I compile that isolated module that doesn't get imported by anyone? Well, the linker eliminates those unused symbols.

2023-01-27 10:18 UTC, ljmf00 commented
Btw, isn't this a compiler bug, there's no `nothrow` attribute but it compiles?

2023-01-28 00:33 UTC, WalterBright commented
> The creation of another module is the shenanigans I was talking about.

How can the compiler determine which one should go first? Isn't it a failure of proper encapsulation for modules that each import each other? (I think some languages don't even allow that.)

2023-01-30 07:25 UTC, FeepingCreature commented
> The creation of another module is the shenanigans I was talking about. And due to how ModuleInfo is designed, it potentially doesn't run. That works on one compiler invocation, but what if I compile that isolated module that doesn't get imported by anyone? Well, the linker eliminates those unused symbols.

If you compile an isolated module, ~all symbols are unused. If a public section is removed, that's a compiler bug.

2024-10-27 07:09 UTC, LightBender commented
PR closed as stalled. If you wish to resurrect it you are welcome to do so.

2024-10-27 07:09 UTC, closed without merging