Better std.algorithm.comparison.clamp error messages
dlang/phobos pull request #8717
Opened 2023-03-14 12:11 UTC by burner

2023-03-14 15:14 UTC, RazvanN7 requested changes

2023-03-14 15:14 UTC, RazvanN7 commented on changelog/clamp_assert_message.dd
> +Better static assert messages for `std.algorithm.comparion.clamp`
```suggestion
Better static assert messages for `std.algorithm.comparison.clamp`
```

2023-03-14 15:14 UTC, RazvanN7 commented on changelog/clamp_assert_message.dd
> +Up until now `clamp` used a template constraint to check if the passed types
```suggestion
Up until now, `clamp` used a template constraint to check if the passed types
```

2023-03-14 15:14 UTC, RazvanN7 commented on changelog/clamp_assert_message.dd
> +could be used. If it were not, it was very tedious to figure out why.
```suggestion
could be used. If they were not, it was very tedious to figure out why.
```

2023-03-14 15:14 UTC, RazvanN7 commented on changelog/clamp_assert_message.dd
> +As the template constraint is not used to overload the symbol template
```suggestion
As the template constraint is not used for overload resolution
```

2023-03-14 15:14 UTC, RazvanN7 commented on changelog/clamp_assert_message.dd
> +function, the constrains are move into static asserts with expressive error
```suggestion
the constraints are moved into static asserts with expressive error
```

2023-03-14 15:14 UTC, RazvanN7 commented on std/algorithm/comparison.d
> +    // Once that is fixed, we can simply use the ternary in both the template constraint
This comment is not accurate anymore if the constraint is removed.

2023-03-14 15:14 UTC, RazvanN7 commented on std/algorithm/comparison.d
> +            : val)));
I am confused as to why this assert is used given that no error message is provided.

2023-03-15 10:24 UTC, burner commented
@RazvanN7 awesome review thank you, arguable better than the PR itself.

2023-03-15 10:33 UTC, RazvanN7 reviewed
Thanks. A few nits and we are good to go.

2023-03-15 10:33 UTC, RazvanN7 commented on std/algorithm/comparison.d
> +            , "' must be implicitly convertable to type of T1 '"
```suggestion
            , "' must be implicitly convertible to type of T1 '"
```

2023-03-15 10:33 UTC, RazvanN7 commented on std/algorithm/comparison.d
> +            , "' must be implicitly convertable to type of T1 '"
As per: https://whichiscorrect.com/convertible-vs-convertable/

2023-03-16 09:04 UTC, RazvanN7 approved these changes

2023-03-16 09:05 UTC, merged

2023-03-17 08:17 UTC, burner commented
@RazvanN7 thank you