Add to PhobosV3 memory allocators from ProjectSidero
dlang/phobos pull request #9078
Opened 2024-10-30 16:44 UTC by rikkimax

I got a bit sick of people saying allocators won't be coming.

So here we go, here are my ~2 year old allocators.

Some key differences from PhobosV2:

1. If something is there, it is complete.
2. Alignment is a property of the allocator, not something you can request.
3. Struct only for the allocator (I would love to use classes, but no RC support).
4. No shared allocator, either it is appropriate to use or you are in a specialized use case and shouldn't be going virtual.
5. Uses ``void[]`` everywhere.
6. Annotated for positive annotation (``export``) and negative annotation (``@hidden``).

2024-10-30 17:05 UTC, pbackus requested changes
Use of `@trusted` on functions that may free aliased memory is unsound. These functions must be `@system`.

2024-10-30 17:05 UTC, pbackus commented on phobos/sys/allocators/mapping/malloc.d
> +@nogc scope pure nothrow @trusted:
This use of `@trusted` here is unsound, because it allows `@safe` code to free memory that may still be pointed to by references other than the `void[]` passed to `deallocate`.

Even though `@safe` code cannot read from a `void[]` directly, it is considered [safe aliasing][1] to (for example) cast a `void[]` to a `const(ubyte)[]` and read the raw byte values from the memory it points to. So a dangling `void[]` is not a [safe value][2].

[1]: https://dlang.org/spec/function.html#safe-aliasing
[2]: https://dlang.org/spec/function.html#safe-values

2024-10-30 17:05 UTC, pbackus commented on phobos/sys/allocators/mapping/mmap.d
> +    @nogc scope pure nothrow @trusted:
This use of `@trusted` is unsound, for the same reason given above.

2024-10-30 17:05 UTC, pbackus commented on phobos/sys/allocators/mapping/virtualalloc.d
> +    @nogc scope pure nothrow @trusted:
This use of `@trusted` is unsound, for the same reason given above.

2024-10-30 17:05 UTC, pbackus commented on phobos/sys/allocators/mapping/virtualalloc.d
> +    @nogc scope pure nothrow @trusted:
This use of `@trusted` is unsound, for the same reason given above.

2024-10-30 17:10 UTC, rikkimax commented on phobos/sys/allocators/mapping/malloc.d
> +@nogc scope pure nothrow @trusted:
I understand that, but as a library, we cannot solve lifetime management at this level.

If you wish to argue that no allocator can be ``@safe``, then please do that and if successful I'll adjust everything to take it into account.

2024-10-30 17:36 UTC, pbackus commented on phobos/sys/allocators/mapping/malloc.d
> +@nogc scope pure nothrow @trusted:
My argument is: functions that can cause [unsafe values][1] or [unsafe aliasing][2] to occur in `@safe` code cannot have [safe interfaces][3], and therefore cannot be marked as `@trusted`.

I've already explained how these `deallocate` and `reallocate` functions can cause unsafe values to occur in `@safe` code. It follows, necessarily, that they cannot be `@trusted`.

I'm not asking you to solve lifetime management. I'm aware that there are a lot of obstacles to making allocators `@safe`. I'm just asking you to annotate these functions correctly.

[1]: https://dlang.org/spec/function.html#safe-values
[2]: https://dlang.org/spec/function.html#safe-aliasing
[3]: https://dlang.org/spec/function.html#safe-interfaces

2024-10-30 17:39 UTC, rikkimax commented on phobos/sys/allocators/mapping/malloc.d
> +@nogc scope pure nothrow @trusted:
I ask for the argument so that a discussion will occur, not so that you can convince me. I understand why, and recognize that it is valid.

2024-10-31 02:17 UTC, rikkimax commented on phobos/sys/allocators/mapping/malloc.d
> +@nogc scope pure nothrow @trusted:
The allocator code itself is perfectly safe, that's not the issue, its all to do with the arguments being passed in and how its being called.

I.e. use after free, double free.

I'm ok with saying it is ``@system``, given the very broad user base.

Unless @jmdavis can argue differently, it seems we are all in agreement about the motivation to change this code over to ``@system``.

2024-10-31 05:08 UTC, jmdavis commented on phobos/sys/allocators/mapping/malloc.d
> +@nogc scope pure nothrow @trusted:
> The allocator code itself is perfectly safe, that's not the issue, its all to do with the arguments being passed in and how its being called.

Then it has to be `@system`, because it's not guaranteed that using the API will result in code that's memory-safe. Barring compiler bugs or bugs in `@trusted` code, it's supposed to be impossible to have memory-safety bugs in `@safe` code no matter what you do, which means that the API must be memory-safe regardless of what you do with it in `@safe` code. If the memory-safety of the API depends on how you use it in `@safe` code, then it must be `@system`.

As soon as something like having had to have called another function first, or calling the same function multiple times with the same argument, or doing something with an argument after passing it to a function could result in memory-safety issues, then `@trusted` isn't appropriate for that function. An `@trusted` function _can_ be unsafe in cases where you give it a bad argument that can only be obtained in `@system` code (e.g. because it's a pointer to garbage, or a pointer to the stack was leaked beyond the point that it was valid), just like that could happen with an `@safe` function, but if there is any way that purely `@safe` code could call that function and not be memory-safe, then it must be left `@system`; otherwise, we're breaking the promise of memory-safety that `@safe` is supposed to give. From the perspective of the caller, there should never be any difference between `@safe` and `@trusted`. The only difference is whether the compiler did the verification for memory-safety or whether the programmer did.

So, for instance, it might be valid to mark a `malloc` function as `@trusted` (since the worst that that would typically do is leak memory), but it would never be appropriate to mark a `free` function as `@trusted`, since it's not realistically possible for a `free` function to protect itself against double-frees and the like, and it can't guarantee that you won't use the pointer after it's been freed. Code that uses `malloc` and `free` together can be vetted for memory-safety and then marked as `@trusted` if its API is memory-safe, but `free` itself can't be `@trusted`.

So, while I can't speak to what in these modules is appropriate to mark as `@trusted` without spending the time to study it all in detail, I would be very surprised if it were appropriate to mark it all with `@trusted`. Either way, explicitly marking it with `@system` shouldn't be necessary, since the compiler will infer that, but IMHO, the correct course of action here is to remove the `@trusted:` and then vet individual functions for `@trusted` where appropriate. And we need to be _very_ careful about what we mark with `@trusted`, because we don't want to make the promise of memory-safety and then not deliver just because we were a tad overzealous about presenting an API where someone didn't need to use `@trusted` themselves.

This really should be the case with any and all `@trusted` code, but with something like druntime or Phobos, we need to be that much more careful, since it's used by basically everyone.

> Unless @jmdavis can argue differently, it seems we are all in agreement about the motivation to change this code over to @system.

Yes. Mark non-templated functions with `@safe` where the compiler thinks that they can be `@safe`, and then mark individual `@system` functions as `@trrusted` when using them in `@safe` code cannot result in memory-safety bugs no matter what that `@safe` code does with them.

2024-10-31 05:59 UTC, rikkimax commented on phobos/sys/allocators/mapping/malloc.d
> +@nogc scope pure nothrow @trusted:
Okay everything is ``@system``, and I've added a bit into the ``package.d`` file module ddoc comment specifically upon it.

2024-10-31 06:06 UTC, rikkimax commented
Okay, me Paul and Jonathan are in agreement about allocators must be entirely ``@system``, i.e. use after free and double free errors are examples of why it has to be.

It is an example of why I recommend using containers (even dynamic array) to manage memory, rather than interact with an allocator directly.

The next question that needs an answer to as this has been asked in relation to v2, is related to the GC allocator being ``@nogc``. I have it setup along with the rest of library as ``@nogc``. From a practical stance, this will offer the best user experience, I see no reason to remove ``@nogc`` from anywhere.

2024-10-31 07:21 UTC, jmdavis commented
> The next question that needs an answer to as this has been asked in relation to v2, is related to the GC allocator being @nogc. I have it setup along with the rest of library as @nogc. From a practical stance, this will offer the best user experience, I see no reason to remove @nogc from anywhere.

I don't know what the GC allocator is doing or how you could possibly mark it as `@nogc`, but if it actually uses GC functions or interacts with the GC in any way, then it should most definitely _not_ be `@nogc` (and I would think that at least some of its functions would be interacting with the GC if it's a GC allocator). If the compiler will let whatever a function is doing be marked `@nogc`, then that should be fine (and I could easily see it being the case that some of the functions don't actually use the GC), but if you're doing anything like casting to `@nogc`, then I think that that's completely inappropriate. As a general rule, if you have to cast to change any attributes or force it via bindings or whatnot, then that's an enormous red flag (e.g. IMHO, it was a huge mistake to try to have versions of `malloc` or `free` which were `pure`; it's a bug factory in the making). If the compiler agrees that an attribute is correct for a piece of code, then great, but if we have to do anything to force it, then we should be very reticent to do so, and we should be _extremely_ careful about it in the rare case where we decide to do so.

We're also going to have to have discussions on how we want to use `@nogc` in general, since it's clear that a lot of people make incorrect assumptions about it on a regular basis (like that it can't allocate). However, in the case of allocators, they're obviously allocating, and aside from an allocator that allocates with the GC, they presumably aren't going to be using the GC, and folks are going to want to use them in `@nogc` code, so `@nogc` would be appropriate. But any function that _actually_ uses the GC, should not be marked with `@nogc`.

In any case, I will say that while I'm fine with giving this a cursory glance, I'm not going to spend the time to review it in detail (and honestly, it's way too much code to review all at once). Personally, I think that if you ever need allocators, you're in a very dark place where I do not want to be, and I don't want to see them used in Phobos' API anywhere outside of the actual allocator modules - and I'd be perfectly fine with them not existing in Phobos at all. I don't feel so strongly about that that I'm going to fight to keep them out of Phobos (and clearly, there are folks who very much want them), but if we start doing like C++ did and templating stuff on allocators, I think that we have a serious usability problem. As it is, those template arguments are almost never used in C++.

Either way, because I would avoid allocators like the plague, I'm likely not the right person to be making decisions on what exactly their API should look like. I can comment on general language issues, but if an issue is truly allocator-specific, other people (like Paul) are far better qualified than I am. Personally, I think that outside of very niche code, it's a mistake to use allocators (though there are certainly some high performance use cases where they're needed).

2024-10-31 07:47 UTC, LightBender commented
My thoughts. 

First. This is an absolutely gargantuan PR. @rikkimax, is there any way we can split this up in to more digestible chunks? While on the topic splitting things up, would it be possible to split `Ternary` out into a separate PR? `typecons` is next on our list so it would be a timely addition.

Second. Allocators have been a perennially contentious topic, with some like @jmdavis being of the opinion that we should not even have them because they are so specialized. And if they are agreed to be included, I am sure that the community has deeply held opinions on what they should look like. @pbackus I know this is a big ask, but would it be possible to review @rikkimax's design and determine if it is suitable for Phobos and how it compares to the existing design? It does not need to be a detailed code review, just enough to get an understanding of it. I know that the existing design has it's flaws and I think the community will be most curious to hear about how this design stacks up against it.

Third. Once the first two items are done, we can open this up to the community for discussion on the design, detailed code review, and whether or not we should even have allocators. This is a huge component and I would feel uncomfortable merging this without a very thorough community discussion and review process.

2024-10-31 08:55 UTC, rikkimax commented
Ternary can certainly be split out.

As for contents, ``phobos.sys.allocators.stats``, ``phobos.sys.allocators.alternatives`` and ``phobos.sys.allocators.mapping`` have 1:1 comparable implementation in v2, and a subset of ``phobos.sys.allocators.buffers`` have comparable implementation in v2, although what is in there may not be complete in v2. ``phobos.sys.allocators.api`` is a subset of the interface stuff, i.e. no aligned allocation or ``IAllocator`` vs ``ISharedAllocator``.

``phobos.sys.allocators.locking``, and ``phobos.sys.allocators.utils`` is new.

From my perspective, there isn't a whole lot that specifically needs looking at in terms of appropriateness of inclusion. As long as ``phobos.sys.allocators.api`` is correct, then its just a matter of verify that everything at the scope level is where it needs to be.

We can improve and fix bugs later.

2024-10-31 17:52 UTC, pbackus commented
Just looking at `phobos.sys.allocators.api`, it seems like the main differences from `std.experimental.allocator` are:

1. **Fewer methods.** For example, both `alignedAllocate` and `expand` are missing.
2. **Reference counting is part of the allocator API.** Individual allocators must opt in to reference counting by implementing the `refAdd` and `refSub` methods.
3. **Thread-safety relies on a `NeedsLocking` flag instead of `shared`.** Not a huge deal given the current state of `shared`, but something we might regret as the language continues to evolve.

2024-10-31 18:02 UTC, pbackus commented
Re: should Phobos 3 have allocators.

Just as the purpose of the range API is to serve as a common interface between generic algorithms and sources of data, **the purpose of an allocator API is to serve as a common interface between generic containers and sources of memory.**

So, instead of asking "should we have allocators," what we should ask is, "should we have allocator-aware containers"?

Given the current state of the D language (i.e., ignoring unreleased/experimental features), it is impossible to implement generic containers that are both (a) `@safe`, and (b) allocator-aware. I have written about why this is the case in exhaustive detail [here][1] and [here][2].

Personally, if we can only choose one, my vote would go to `@safe`, which means **I would vote no on allocators in Phobos 3.**

[1]: https://forum.dlang.org/thread/jsuraddtynhjoaikqprs@forum.dlang.org
[2]: https://gist.github.com/pbackus/29c520bc4e1f4aa075c9171db791d234

2024-10-31 21:56 UTC, pbackus commented
> In neither article do you go into the fact that there is a subset of data structures that can use allocators and be `@safe`.
>
> Specifically if the data structure does not allow access to internal memory (at least in `@safe` code)

I take it as given that Phobos 3's containers must allow by-`ref` access to their elements. If our containers are missing important features, it doesn't matter how `@safe` they are; nobody will want to use them.

2024-10-31 22:03 UTC, rikkimax commented
> > In neither article do you go into the fact that there is a subset of data structures that can use allocators and be `@safe`.
> > Specifically if the data structure does not allow access to internal memory (at least in `@safe` code)
> 
> I take it as given that Phobos 3's containers must allow by-`ref` access to their elements. If our containers are missing important features, it doesn't matter how `@safe` they are; nobody will want to use them.

Some of my data structures do not offer this intentionally and that is a key characteristic for their usage.

We can have multiple variations of a data structure, we do not need to gatekeep based on the perceived requirements of a different variation.

2025-02-07 19:48 UTC, LightBender commented
@rikkimax I am going to close this for now to de-clutter the PR list. This topic is going to require much more significant debate which will probably take place on a scale that GitHub lacks the capability to adequately express.

2025-02-07 19:48 UTC, closed without merging